open-power/snap

hardware/Makefile, hardware/setup/create_framework.tcl, hardware/sim/run_sim, hardware/snap_settings
it is now possible to build a NVME image without denali
=> HW: fix for #287

hardware/sim/testlist.sh
=> SIM: renamed stage2 to snap_example inside testlist.sh

software/examples/action_checksum.c
Multi threading corrected for sponge
=> Hls examples new clean

hardware/sim/testlist.sh, software/examples/snap_example.c, software/examples/snap_example_ddr.c, software/examples/snap_example_set.c, software/scripts/a_test.sh, software/scripts/b_test.sh, software/scripts/c_test.sh
Some changes in for Software tools
=> Snap example fixes

hardware/Makefile, hardware/setup/snap_build.tcl
=> HLS: clean up the create HLS code flow

software/scripts/a_test.sh, software/scripts/b_test.sh, software/scripts/c_test.sh, software/scripts/snap_jenkins.sh, software/tools/snap_find_card, software/tools/snap_maint.c
I added a script file to run Jenkins Tests on our "tul2" Box in the lab.
The Script starts right after a new Image was Made for KU3 (for now, FGT will follow)
The New Image will be flashed, and tested. Flash is still marked out. The test will only start if no one else
uses out test machine.
=> Jenkins hw test

README.md, hardware/README.md
hardware/README.md : correct reference to action_examples/memcopy #323
=> Fix #323 Correct ACTION_ROOT, add Nallatech reference

hardware/action_examples/hls_hashjoin/hls_hashjoin.cpp, hardware/action_examples/hls_memcopy/action_memcopy.H, hardware/action_examples/hls_memcopy/hls_memcopy.cpp, hardware/action_examples/hls_search/action_search.H, hardware/action_examples/hls_search/hls_search.cpp, hardware/action_examples/hls_sponge/hls_checksum.cpp, hardware/action_examples/hls_sponge/sha3.cpp, software/examples/action_search.c, software/examples/snap_memcopy.c, software/examples/snap_search.c, software/scripts/a_test.sh, software/scripts/b_test.sh, software/scripts/c_test.sh, software/scripts/snap_jenkins.sh, software/tools/snap_find_card, software/tools/snap_maint.c
Memcopy : bigger buffer size
Search : small corrections (correction of Issue #315)
Sponge : push code used for benchmark - adding ifdef to remove unused and non optimized code
=> HLS examples : memcpy + search + sponge modifications

software/examples/Makefile
=> HLS: Adding more smooth action software integration

software/tools/snap_maint.c
Add some code to display Version Register in Verbose mode.
Set -v or -vv flags to get this info, Clean up code (Verbose Messages)
Add code to display "FPGA Up Time"
=> Issue_313:

hardware/action_examples/hls_sponge/hls_checksum.cpp, software/examples/action_checksum.h, software/examples/snap_checksum.c
=> HLS sponge: Push the all-modes release

hardware/Makefile, hardware/setup/create_framework.tcl, hardware/setup/snap_bitstream_post.tcl, hardware/setup/snap_bitstream_pre.tcl, hardware/setup/snap_build.tcl, hardware/setup/snap_config.sh, hardware/snap_settings
new factory image build flow based on "Build: Create factory bitstream when GOLDEN_IMAGE=TRUE #306"
=> Bitstream: Added factory image build option

hardware/sim/testlist.sh
this time jusxst the testlist, no MAkefile anymore
=> remove python to reduce dependencies, add functions

hardware/setup/snap_build.tcl
Signed-off-by: Kenneth Hill <khill@us.ibm.com>
=> Build: Correct minor typo in snap_build.tcl

software/examples/action_search.c
=> HLS search: sync action code and application code

hardware/setup/snap_build.tcl
Signed-off-by: Joerg-Stephan Vogt <jsvogt@de.ibm.com>
=> Fix #375, WNS instead of TNS, handle TNS=0.000

software/examples/snap_example_ddr.c, software/tools/snap_maint.c
* snap_maint output format
* snap_example_ddr default and address
=> Small snap_maint and and snap_example_ddr fixes

hardware/sim/run_sim
Please check, if this solves your problems
=> SIM: kill child processes of applications of app, if simulation dies

software/examples/snap_search.c, software/include/libsnap.h, software/lib/snap.c
=> HLS search: Switch to queue mode

software/lib/snap.c
=> SW: Fix error handling when polling for job completion

hardware/README.md, hardware/doc/Bitstream_flashing.md, hardware/setup/FGT/snap_nvme.xdc, hardware/setup/build_mcs.tcl, hardware/setup/flash_mcs.tcl
How to build the factory image, the mcs file, and finally flash an card from scratch using the Xilinx JTAG adapter
=> DOC: Factory image and flashing cards from scratch

actions/Makefile, actions/README.md, actions/software.mk, hardware/Makefile, hardware/README.md, software/tools/Makefile
=> Build: Fix_Cleanup_if_SNAP_ROOT_is_not_set

hardware/sim/testlist.sh
=> wrong testlist return, correct intersect selection

hardware/sim/testlist.sh
xsim needs longer for intersect tests, so I increased the timeout values.
=> longer timeout values for intersect running with xsim

hardware/sim/run_sim
=> run_sim fails in jenkins, extend timeout to start simulation

actions/hls_memcopy/tests/test_0x10141000.sh, actions/scripts/snap_jenkins.sh
I made some fixes to get hls memcopy to run on tul2,
=> Sw jenkins fix

hardware/Makefile, hardware/README.md, hardware/setup/create_framework.tcl, hardware/setup/export_irun.tcl, hardware/setup/export_xsim.tcl, hardware/snap_settings
Fixing HW build for HLS actions in non pr-flow
=> HLS: Fixing path to action_root in non pr-flow

hardware/setup/snap_build.tcl, hardware/setup/snap_cloud_build.tcl, hardware/setup/snap_cloud_merge.tcl
Fix for #422: added exit 42 to the write_bitstream command
=> build: fix for defect #422

actions/hdl_example/hw/action_axi_master.vhd, actions/hdl_example/hw/action_axi_nvme.vhd, actions/hdl_example/hw/action_example.vhd_source, actions/hdl_example/hw/action_wrapper.vhd_source, actions/hls_nvme_memcopy/hw/hls_nvme_memcopy.cpp, hardware/hdl/core/action_types.vhd, hardware/hdl/core/psl_accel_fgt.vhd_source, hardware/hdl/core/psl_accel_types.vhd_source, hardware/hdl/hls/action_wrapper.vhd_source
Suggesting these changes to the branch HLS_nvme_memcopy2
=> Changes for HLS_nvme_memcopy2

actions/scripts/snap_jenkins.sh
I added 2 patches to get hls memcopy and hls nvme test to work on jenkins.
=> Fix jenkins

hardware/snap_check_psl
=> added md5 sum for the new FGT PSL_DCP

hardware/Makefile
Minor typo in Make recipe cloud_action
=> PR Flow: Fix typo in hardware/Makefile

ActionTypes.md, actions/hls_helloworld/Makefile, actions/hls_helloworld/doc/README.md, actions/hls_helloworld/hw/Makefile, actions/hls_helloworld/hw/README.md, actions/hls_helloworld/hw/action_uppercase.H, actions/hls_helloworld/hw/action_uppercase.cpp, actions/hls_helloworld/include/action_changecase.h, actions/hls_helloworld/sw/Makefile, actions/hls_helloworld/sw/README.md, actions/hls_helloworld/sw/action_lowercase.c, actions/hls_helloworld/sw/snap_helloworld.c, actions/hls_memcopy/hw/action_memcopy.H, actions/hls_memcopy/hw/hls_memcopy.cpp, actions/hls_memcopy/sw/snap_memcopy.c, scripts/Kconfig, snap_env
=> Hls helloworld and memcopy

hardware/README.md
=> Fix hardware/readme

actions/hls_helloworld/hw/action_uppercase.cpp, actions/scripts/create_run_hls_script.sh
=> corrected a typo in tb path in scripts/create_run_hls_script.sh

hardware/setup/create_framework.tcl, hardware/setup/create_ip.tcl
This change request implements the necessary changes for issue #395.
=> IPs: Adding support for user IPs

scripts/Kconfig
Signed-off-by: Kenneth Hill <khill@us.ibm.com>
=> Fix Kconfig PR variable

actions/hls_memcopy/tests/test_0x10141000.sh
Script was not able to find snap_maint. 
=> Correct Path to tools

Makefile, hardware/Makefile
`Makefile`:
Adding target `apps` together with help message
`hardware/Makefile`:
Unconditional export simulation
Replacing `hw_config` with `hw_project`.
Forcing hw_project
=> Make process changes

README.md
Signed by Lu Yong (luyong@cn.ibm.com)
=> Add one line description to Semptian card support

snap_path.sh
This is a proposal for the change requested by @bmesnet via eMail at 2017-11-28
=> snap_path.sh: Adding ACTION_ROOT only if defined

actions/hdl_example/tests/10140000_nvme_test.sh, actions/hls_bfs/tests/test_0x10141004.sh, actions/hls_hashjoin/tests/test_0x10141002.sh, actions/hls_intersect/tests/test_0x10141005.sh, actions/hls_intersect/tests/test_0x10141006.sh, actions/hls_nvme_memcopy/tests/test_0x10141007.sh, actions/scripts/snap_jenkins.sh, software/tools/snap_find_card
This Branch fixes Jenkins tests.
=> Rc fix jenkins

actions/scripts/snap_jenkins.sh
=> Add missing end for file name.

software/lib/snap.c
=> SW: Improve error messages

Makefile, actions/Makefile, actions/hdl_nvme_example/sw/Makefile, actions/hls_memcopy/sw/Makefile, actions/software.mk, software/Makefile, software/README.md, software/config.mk, software/lib/Makefile, software/tools/Makefile, software/tools/cfg_snap_actions.pl
This set of changes also includes what Alexandre liked to have in there too.
Let us wait until the majority of the automatic testing was done fine before
we consider merging this.
=> Build: New build fixpus

software/lib/snap.c
=> SW: Fix build break

software/tools/Makefile
=> Build: Add rpath to tools

actions/hdl_example/sw/snap_example.c, actions/hdl_example/tests/10140000_kill_test.sh
Testcase brings card into unusable state. Fortunately I have not seen system breakage yet.
=> RAS: Sudden death testcase

hardware/Makefile
=> Build: Add missing cleanup for PSLSE

hardware/hdl/core/dma_buffer_capi10.vhd_source, hardware/hdl/core/dma_buffer_capi20.vhd_source, hardware/hdl/core/dma_capi10.vhd_source, hardware/hdl/core/dma_capi20.vhd_source
I have removed a lot of unnecessary reset signals in the DMA logic. This should reduce the overall SNAP routing utilisation.
=> HW build: Improve routing

actions/hls_intersect/tests/test_0x10141005.sh, actions/hls_intersect/tests/test_0x10141006.sh
=> HLS Intersect Jenkins fix

hardware/Makefile, hardware/snap_check_psl, snap_env
added an PSL_DCP outdated checker
=> HW: improve PSL_DCP checking

Makefile, hardware/Makefile, hardware/setup/create_framework.tcl, snap_env
Hi @kenhill please have a look at this and merge it into your branch (via "rebase and merge") if it meets your requirements
=> Cloud merge modified

Makefile, hardware/Makefile, hardware/setup/create_framework.tcl, snap_env
=> Skipping ACTION_ROOT check for cloud merge

actions/hdl_nvme_example/sw/snap_cblk.c, actions/hdl_nvme_example/tests/test_0x10140001.sh
=> CBLK: Adding fix for missing output file

actions/hdl_nvme_example/hw/action_axi_nvme.vhd, actions/hdl_nvme_example/hw/action_axi_slave.vhd, actions/hdl_nvme_example/hw/action_nvme_example.vhd, actions/hdl_nvme_example/sw/snapblock.c
Allowing read and write requests for every slot
=> hdl_nvme_action: Completely restructured

actions/hls_sponge/sw/snap_checksum.c, actions/hls_sponge/tests/test_0x10141001.sh, software/lib/snap.c
The shell script was missing -C <card>.
I also fixed errno in snap lib.
=> HLS Sponge: Rework some problems in sponge.

software/lib/snap.c
=> Fix for #571

ActionTypes.md, actions/hls_bfs/hw/action_bfs.H, actions/hls_bfs/hw/hls_bfs.cpp, actions/hls_helloworld/hw/action_uppercase.H, actions/hls_helloworld/hw/action_uppercase.cpp
Refine two actions: hls_helloworld and hls_bfs. 
Verified with Vivado/Vivado_hls 2016.4
=> HLS type casting optimize

hardware/setup/flash_mcs.tcl, hardware/sim/README.md, hardware/snap_check_psl
+ typo
+ small flash_mcs.tcl fix
=> Add PSL DCPs with reset fix to snap_check_psl

hardware/hdl/core/psl_fpga_n250sp.vhd_source
=> fixed syntax errors in psl_fpga_n250sp.vhd_source

defconfig/N250SP.hdl_example.SDRAM.defconfig, defconfig/N250SP.hls_bfs.defconfig, defconfig/N250SP.hls_sponge.defconfig, hardware/sim/fastest.parms
=> adding more defconfig files for N250SP to enhance testing

actions/hdl_example/sw/snap_example.c, hardware/hdl/core/axi_dma_shim.vhd, hardware/hdl/core/ctrl_mgr.vhd, hardware/hdl/core/dma_capi10.vhd_source, hardware/hdl/core/dma_capi20.vhd_source, hardware/hdl/core/job_manager.vhd, hardware/hdl/core/mmio.vhd_source, hardware/hdl/core/snap_core.vhd_source, hardware/hdl/core/snap_core_types.vhd_source, hardware/setup/snap_link.xdc, software/include/snap_hls_if.h, software/include/snap_regs.h, software/lib/snap.c
Second try after rebasing to fixed master
=> Adding support for llcmd abort

hardware/setup/create_framework.tcl, hardware/setup/create_ip.tcl, hardware/setup/create_nvme_host.tcl, hardware/setup/snap_build.tcl, hardware/snap_check_psl
Includes all changes that needed for Vivado17.4
=> Viv17 changes

hardware/setup/snap_build.tcl, hardware/snap_check_psl
=> Allow new adku3 psl

hardware/setup/create_framework.tcl, hardware/setup/create_ip.tcl
=> viv17: switch back target language to VHDL

hardware/README.md
It is not easy to find documentation on existing NVMe examples, hope this would improve a bit
Thanks
=> detail on the available examples

scripts/Kconfig, snap_env
Signed-off-by: Sven Boekholt <boekholt@de.ibm.com>
=> Config: Adding info that N250SP is in preparation

hardware/doc/NVMe.md
Signed-off-by: Frank Haverkamp <haver@vnet.linux.ibm.com>
=> Doc: Update NVMe.md

hardware/setup/create_framework.tcl, hardware/setup/snap_cloud_build.tcl
I found a workaround for the problem #613. Please test it in our cloud environment and merge it to master if the test looks good.
=> Sr10426478 workaround

Makefile
This is a proposal for solving issue #603.
=> Config: Don't clean hardware w/o config change

actions/scripts/snap_jenkins.sh
This Patch will allow us to test SNAP in one Test machine at the same time. Only Flash update will
block. There is a new Option (-C) which can be uses to select a Card for test.
=> Jenkins multi

defconfig/ADKU3.hls_helloworld.defconfig, defconfig/N250SP.hdl_example.BRAM.defconfig, defconfig/N250SP.hls_hashjoin.defconfig, defconfig/N250SP.hls_intersect.defconfig, defconfig/N250SP.hls_memcopy.defconfig, defconfig/N250SP.hls_search.defconfig, hardware/sim/testlist.sh
Please review the additions for mor N250SP tests and helloworld enablement
=> More n250 sp

hardware/doc/Bitstream_flashing.md
Signed-off-by: Joerg-Stephan Vogt <jsvogt@de.ibm.com>
=> Updated factory image build procedure, fixes from issue #525

hardware/hdl/core/psl_accel_types.vhd_source, hardware/setup/create_framework.tcl, hardware/setup/create_ip.tcl, scripts/Kconfig
=> HW: Enable SDRAM for sim on N250SP

hardware/snap_check_psl
=> added md5sum for psl233_viv17.4_vsec400h_Feb23

hardware/setup/export_irun.tcl, hardware/setup/export_questa.tcl, hardware/setup/export_xsim.tcl
=> add a comment into export_irun.tcl to point to the Xilinx AR

software/Makefile
=> SW build: Including snap_env.sh into software/Makefile

software/tools/snap_find_card
=> Fix snap_find_card case-statement

actions/hdl_example/sw/snap_example.c
I made some fixes for snap examlpe to end the test if
attach or detach fails. Please Verify and approve.
=> Exit test if attach or detach fails.

actions/hdl_example/sw/snap_example_set.c, hardware/hdl/core/dma_capi20.vhd_source, hardware/sim/core/top_capi20.sv_source, hardware/sim/testlist.sh, scripts/Kconfig, software/include/snap_regs.h, software/lib/snap.c, software/tools/snap_maint.c
#665: fixed wram_raddr_q handling in dma_fsm_q
=> fixed issue #665

hardware/doc/Bitstream_flashing.md
This pull request replaces #681. I did rebase the branch Alexandre created, so this pull request only contains the relevant changes.
=> 8k5 data and latest capi flash script info rebased

hardware/setup/create_framework.tcl
=> use synthese option rebuilt instead of none

actions/hdl_nvme_example/sw/snapblock.c
Please Approve.
Signed-off-by: Eberhard S. Amann <esa@zaiusboe.aus.stglabs.ibm.com>
=> Remove unused if to fix compile error.

defconfig/N250S.hls_helloworld.defconfig, defconfig/N250SP.hls_helloworld.defconfig, defconfig/S121B.hls_helloworld.defconfig, hardware/sim/testlist.sh
adding helloworld defconfig files, but disable N250SP, until more than 128B DMA xfers are possible. See #686
=> Complete helloworld

actions/hls_nvme_memcopy/hw/hls_nvme_memcopy.cpp, actions/hls_nvme_memcopy/hw/hw_action_nvme_memcopy.H, actions/hls_nvme_memcopy/sw/Makefile, actions/hls_nvme_memcopy/sw/snap_nvme_memcopy.c, actions/hls_nvme_memcopy/sw/sw_action_nvme_memcopy.c
Signed-off-by: Alexandre Castellane alexandre.castellane@fr.ibm.com
=> refreshed the nvme application

software/config.mk
Set default value in case there is no git.
=> Remove some unused lines. Set Version to git tag.

actions/hls_intersect/README.md, scripts/Kconfig
Signed by Lu Yong (luyong@cn.ibm.com)
=> Bad timing warning on hls_intersect

hardware/setup/create_ip.tcl
=> fixed typo inteconect in create_ip

hardware/snap_check_psl
=> tagged old PSL DCPs as outdated

hardware/Makefile, hardware/setup/create_ip.tcl, hardware/setup/snap_bitstream_step.tcl, hardware/setup/snap_build.tcl, hardware/setup/snap_cloud_build.tcl, hardware/setup/snap_cloud_merge.tcl, hardware/setup/snap_impl_step.tcl, hardware/setup/snap_synth_step.tcl, snap_env
Using common scripts for the snap build, cloud build and the cloud merge flow
=> Script clean up

hardware/hdl/core/psl_accel_ad8k5.vhd_source, hardware/hdl/core/psl_accel_adku3.vhd_source, hardware/hdl/core/psl_accel_n250s.vhd_source, hardware/hdl/core/psl_accel_n250sp.vhd_source, hardware/hdl/core/psl_accel_s121b.vhd_source, hardware/hdl/core/psl_fpga_ad8k5.vhd_source, hardware/hdl/core/psl_fpga_adku3.vhd_source, hardware/hdl/core/psl_fpga_n250s.vhd_source, hardware/hdl/core/psl_fpga_n250sp.vhd_source, hardware/hdl/core/psl_fpga_s121b.vhd_source, hardware/setup/create_framework.tcl, hardware/sim/core/top_capi10.sv_source, hardware/sim/core/top_capi20.sv_source
=> removed all comments that I have added during the newDDRresetSchema work

hardware/hdl/core/psl_fpga_n250sp.vhd_source, hardware/setup/N250SP/create_ip.tcl, hardware/setup/N250SP/patch_pcie.sh, hardware/setup/create_framework.tcl
=> PSL9 board support cleanup

hardware/hdl/core/dma_buffer_capi20.vhd_source, hardware/hdl/core/dma_capi20.vhd_source, hardware/setup/snap_config.sh
=> added 64 byte alignment support for N250SP

hardware/setup/N250S/pr_snap_nvme_pblock.xdc, hardware/setup/snap_cloud_merge.tcl
Use open_checkpoint and read_checkpoint to merge the action and static DCP. With this commands, the static DCP stays in the locked state.
=> Cloud merge imp

actions/hdl_example/sw/snap_example_set.c, hardware/sim/testlist.sh
=> snap_example_ddr mult of 64

snap_env
=> snap_env: Fixing typo in condition for if statement

hardware/Makefile, hardware/sim/testlist.sh, hardware/sim/xsaet.tcl
and replace bash let with arithmetic expansion to get rid of false fails in intersect testing
=> use PSLSE root Makefile

hardware/setup/flash_mcs.tcl
Signed-off-by: Kenneth Hill <khill@us.ibm.com>
=> Fix Typo in flash_mcs.tcl

scripts/Kconfig
Signed-off-by: Sven Boekholt <boekholt@de.ibm.com>
=> Change descriptions for card selection

actions/hls_sponge/hw/action_sponge.cpp
add pragma to support timing with HLS2018.1
=> Issue 755 correction

snap_env
=> correcting issue #773

hardware/setup/build_mcs.tcl, hardware/setup/snap_bitstream_step.tcl, scripts/Kconfig
Correct build_mcs which lost factory_addr at last change
Align format for factory generate bitstream on user generate bitstream
=> Correct build_mcs.tcl which lost factory_addr at last change

actions/hls_memcopy/tests/test_0x10141000_throughput.sh
=> improve large files creation

hardware/setup/snap_bitstream_step.tcl
=> added action name into the bitstream file name

actions/hls_memcopy/tests/test_0x10141000_throughput.sh, actions/hls_mm_test/sw/snap_mm_test.c, actions/hls_mm_test/tests/process.awk, actions/hls_mm_test/tests/test_0x1014100A.sh
Some refinement for throughput test in hls_memcopy: **add -N**
Add tests for snap_mm_test.
=> Test scripts for two actions

README.md
Signed-off-by: luyong6 <luyong@cn.ibm.com>
=> Add Flyslice webpage link

hardware/hdl/core/dma_buffer_capi20.vhd_source, hardware/hdl/core/dma_capi20.vhd_source
=> fix for issue 801

hardware/setup/create_nvme_host.tcl
=> tcl could not handle a list parameter that is comment out

ActionTypes.md
Signed-off-by: David Epping <david.epping@missinglinkelectronics.com>
=> ActionTypes.md: Add MLE network accelerator action types

actions/hls.mk, hardware/Makefile, hardware/setup/create_framework.tcl, hardware/setup/create_ip.tcl, snap_env
=> Renaming link to HLS action sources

doc/README.md
Signed-off-by: Alexandre Castellane <alexandre.castellane@fr.ibm.com>
=> updated supported hardware P9 tables

hardware/sim/testlist.sh
action ID of hdl_helloworld was wrong, resulted in calling hdl_helloworld with action=sponge
=> Helloworld sponge mix

software/tools/snap_find_card
Signed-off-by: Lu Yong <luyong@cn.ibm.com>
=> Add 060d for N250SP

doc/README.md, software/README.md
Add list of useful APIs, description and sequence => /software/README.md
Correct typo in resource enabled for RCXVUP card => /doc/README.md
=> Add API description 

actions/hls_search/sw/snap_search.c
Signed-off-by: Lu Yong <luyong@cn.ibm.com>
=> Fix fallthrough warning on GCC7

hardware/setup/AD9V3/snap_bitstream_pre.tcl, hardware/setup/snap_impl_step.tcl, snap_env
=> re-add the constraints for AD9V3

hardware/doc/Bitstream_flashing.md
Signed-off-by: Alexandre Castellane <alexandre.castellane@fr.ibm.com>
=> flash_doc_update

defconfig/AD8K5.hdl_example.NORAM.FACTORY.defconfig, defconfig/AD9V3.hdl_example.NORAM.FACTORY.defconfig, defconfig/ADKU3.hdl_example.NORAM.FACTORY.defconfig, defconfig/FX609.hdl_example.NORAM.FACTORY.defconfig_b, defconfig/N250S.hdl_example.NORAM.FACTORY.defconfig, defconfig/N250S.hdl_nvme_action.defconfig, defconfig/N250S.hdl_nvme_action_cloud.defconfig, defconfig/N250SP.hdl_example.NORAM.FACTORY.defconfig, defconfig/RCXVUP.hdl_example.NORAM.FACTORY.defconfig_b, defconfig/S121B.hdl_example.NORAM.FACTORY.defconfig, defconfig/S241.hdl_example.NORAM.FACTORY.defconfig_b, doc/README.md
Signed-off-by: Alexandre CASTELLANE <alexandre.castellane@fr.ibm.com>
=> defconfig with FACTORY

actions/hls.mk, snap_env, snap_path.sh, snap_trace
few enhancements + correction of the issue#866
=> Few enhancements

actions/hls.mk
=> correct path of HLS log

actions/hls.mk
=> hls.mk: correct path of hls.log for all vivado releases

hardware/setup/flash_mcs.tcl
=> Fixed flash device in flash_mcs.tcl script for 9V3.

defconfig/U200.hdl_example.SDRAM_DDR_not_wired_yet.defconfig, defconfig/U200.hls_memcopy_DDR_not_wired_yet.defconfig
/hardware/capi2-bsp now pointing to master
=> Sync u200 capi bsp master

actions/hls_hashjoin/sw/snap_hashjoin.c
this should correct the 2 issues you see in jenkins tests
=> Bug correction + board constraints added to ease routing

Makefile, hardware/Makefile, snap_debug_timing, software/tools/snap_maint.c
=> propose next steps to user

hardware/setup/create_framework.tcl
Signed-off-by: Alexandre CASTELLANE <alexandre.castellane@fr.ibm.com>
=> strategy update for flash controller

actions/scripts/snap_jenkins.sh, defconfig/U200.hls_search.defconfig
+ U200.hls_search.defconfig creation (replacing U200.hls_search_DDR_not_wired_yet.defconfig)
+ Added AD9H3 support for snap_jenkins.sh
=> Ad9h3 addition

actions/scripts/snap_jenkins.sh
actions/scripts/snap_jenkins.sh:
- Added 10141009 action (hls_latency_eval)
- Added 1014100c action (hls_scatter_gather)
- Failure return code (RC=99) if action code is not valid
=> Jenkins hls latency eval

actions/scripts/snap_jenkins.sh
Signed-off-by: fmoyen <fabrice_moyen@fr.ibm.com>
=> snap_jenkins.sh: side effect correction when action=10140000

README.md
Signed-off-by: Alexandre Castellane <alexandre.castellane@fr.ibm.com>
=> update README woth oc-accel reference

software/tools/snap_find_card
Snap_find_card modification in order to display physical Card PCI location (like before) but also the PCI location for the virtual PCI Card that lspci command reports.
=> Find card evol

scripts/Kconfig, software/lib/snap.c
=> Minor fixes

software/tools/snap_maint.c
Signed-off-by: acastellane <alexandre.castellane@fr.ibm.com>
=> adding rules comment

actions/hdl_example/tests/10140000_test.sh
Signed-off-by: acastellane <alexandre.castellane@fr.ibm.com>
=> hdl_ex jenkins tst repaired

hardware/Makefile
=> remove debug commented line which prevents compiling pslse

hardware/setup/create_framework.tcl
=> tune for vivado 2020.1
