hardware/Makefile
hardware/snap_settings

Adding check for HLS actions that `$ACTION_ROOT` ends in `vhdl` or in `verilog`
This is a first approach to get a solution for issue #317

Check $ACTION_ROOT

---

hardware/Makefile

Bashisms like "[[ ... ]]" and comparisons with "==" were replaced with sh-compatible expressions.
Signed-off-by: Balthasar Martin <balthasar.martin@student.hpi.de>

Improved /bin/sh compatibility in hardware/Makefile

---

hardware/Makefile
hardware/setup/create_framework.tcl

Another fix for issue #317
- Making sure that psl_fpga is top module for HLS actions
- Cleaning action with `make clean` from `snap/hardware` directory

HW project: Another fix for HLS actions

---

hardware/hdl/core/dma_buffer.vhd

Looks like the NVMe reset sequence fix has solved the NVMe link training issue.

RC dma fix removed

---

software/config.mk
software/examples/Makefile

Using CFLAGS += -std=c99 was not working yet for the library due to a union without a name defined in cxl.h. So using it for the example applications only is the only thing working yet. I talked to Frederic Barrat to have a look.

SW: allow c99 for example code

---

hardware/action_examples/Makefile
software/config.mk

Same as old branch, but not changing the test stuff.
Added -funroll-all-loops to speed up test-applications.
I wonder where my platform specific optimisations ended up ...

Build/SW: Fixing clean rule for example actions, using -funroll-all-loops to build example code

---

actions/hdl_example/sw/snap_example.c
actions/hdl_example/sw/snap_example_ddr.c
hardware/sim/testlist.sh

Added some code for input parameter test. Example code can only be used on a 
64 Byte boundary.

Check snap_example tools Input parameter.

---

actions/hdl_example/hw/action_axi_slave.vhd

The wrong assignment causes only trouble if an action register is written which doesn't exist. 
Signed-off-by: Reiner Rieke <rieke@de.ibm.com>

hdl_example: Fixed wrong register assignment

---

software/lib/snap.c

Attach action did timeout because action_type was set at
snap_queue_alloc(). The following attach compare the action_type
to the action type form card->action_type. No attach was invoke when this
value was set. I added some code to save action type in
action_typeq. This value will later be used to call
snap_snyc_execute_job().

Fix for issue 397:

---

hardware/Makefile
hardware/hdl/core/dma_buffer.vhd_source

Enable flip_bit fix to avoid 64B swap again for FGT card until problem in corresponding PSL is fixed

HW: Enable flip_bit fix for FGT card

---

hardware/sim/testlist.sh

since this works only on hdl_example.

revert writing to DDR for all actions

---

actions/hdl_example/sw/Makefile
actions/hdl_example/sw/snap_example_qnvme.c

This New tool is added to test more functions for SNAP NVME.
I use the CAPI Slave device to copy data from Host to SNAP Card Ram.
The Capi Master device (afu0.0m) is used to Enable native NVME function on NVMW Host controller.
Following NVME SSD tests are done If -r or -w (Write/Read) flag is enabled.
1.) If Write:
Copy Data from CARD RAM to NVME drive
2.) if Read:
Copy Data from NVME to CARD RAM
Copy the data back to Host
Compare data.
Options like -b -o -n are used to increase the NVME Data size.
See -h for help.

New nvme test

---

hardware/sim/core/ddr3_dimm.sv

fixed #415 
SIM: set MEM_BITS to 12 to allow more then 2^10 write data bursts

Sim: fix for issue #415

---

hardware/setup/FGT/snap_nvme.xdc

The statement set_false_path -from [get_ports sys_rst_n] in snap_nvme.xdc is no longer valid and causes critical warnings in the log files. I replaced the set_false_path by a valid on.
set_false_path -from [get_pins nvme_reset_n_q*/C] -to [get_clocks pcie_clk?]

build: fixed set_false_path for the nvme_reset_n_q signal

---

Makefile
hardware/Makefile

This change will allow to run kconfig on the console by calling `make config` (as opposed to target `oldconfig` the target `config` will go through all the configuration options)

Config: Replacing old target config with hw_config

---

hardware/Makefile
scripts/snap_cfg
snap_env

With this change it is possible to define paths and other environment variables in `.snap_env.sh` in a way that they contain config variables that will be replaced with their values only in the evaluation within the make process.
In order to make these definitions persistent, single quotes are required. For example:
'''
export PSL_DCP='/afs/xyz/cards/${FPGACARD}/current/b_route_design.dcp'
'''

Config: Support for "static" variables in .snap_env.sh

---

Makefile
actions/Makefile
hardware/Makefile
snap_env

This change addresses issue #449.
It additionally disables all hardware related targets on non-x86 machines.
On the start of an image build, a message is printed that this will take a while and that the process may be terminated by pressing <CTRL>-C.
Furthermore, calling `make model` directly from the hardware directory w/o a previous configuration via `make snap_config` will now assume `SIMULATOR=nosim` and therefore won't do anything.

Makefile: Help message as default

---

Makefile
hardware/Makefile

Executing `make clean` on Power currently leads to an error, because the target `clean` is disabled on non-x86 platforms. This change is fixing the problem.
Furthermore, I moved the target gitclean from `snap/hardware/Makefile` to `snap/Makefile`.

Makefile fix: Enabling target clean on Power again

---

software/lib/snap.c

To answer to issue #432 SNAP enhancements item 2

add cpu and fpga keyword to SNAP_CONFIG mode tests

---

ActionTypes.md
scripts/Kconfig

I did not find a way to create a dependency between ENABLE_SDRAM and ENABLE_BRAM such that both options are always visible but only one of them is selectable.
Note: Additionally to the Kconfig changes I also modified ActionTypes.md since kconfig is taking care of consistency in the selection of options.

Kconfig advanced settings

---

snap_env

The previous DCP_ROOT check was creating a default dcp directory instead of adding DCP_ROOT to SETUP_EMPTY.

Use snap_env.sh for DCP_ROOT instead of creating default directory

---

scripts/Kconfig

This actions does not appear to support SDRAM and will cause build errors if a user enables SDRAM/BRAM with snap_config

Disable SDRAM/BRAM for hls_helloworld action

---

hardware/sim/run_sim
snap_path.sh

This change is meant to solve issue #502 by adding `$SNAP_ROOT/software/tools` and `$ACTION_ROOT/sw` to `$PATH` in simulation and via a script (`snap_path.sh`) that can be sourced by the user manually.
Should we add documentation for `snap_path.sh`? Where?

ENV: Setting PATH in sim and adding snap_path.sh

---

defconfig/ADKU3.SDRAM.XSIM.PRFLOW.hls_memcopy.defconfig

The old PRFLOW defconfig does not work w/ v1.2.0. Can we tag this v1.2.1?
Signed-off-by: Kenneth Hill <khill@us.ibm.com>

Update PRFLOW defconfig for release v1.2.0

---

Makefile
actions/hdl_nvme_example/README.md
actions/hdl_nvme_example/sw/Makefile
actions/hdl_nvme_example/sw/pp.c
actions/hdl_nvme_example/sw/pp.h
actions/hdl_nvme_example/sw/snap_cblk.c
actions/hdl_nvme_example/sw/snapblock.c
actions/hdl_nvme_example/tests/lbalog_analysis.py
actions/hdl_nvme_example/tests/snap_init.sh
actions/hdl_nvme_example/tests/test_0x10140001.sh
actions/software.mk
hardware/Makefile
hardware/sim/run_sim
software/include/libsnap.h
software/include/snap_internal.h
software/lib/Makefile
software/lib/snap.c
software/scripts/snap_tests.sh
software/tools/Makefile

In this code we include several updates, fixes and enhancements to put together an NVMe block layer with LBA protection. We can prefetch in positive, negative or in both directions. Include also a prototype of a more flexible prediction approach, but that is not enabled yet.

CBLK: NVMe Blocklayer with LBA pre-fetching updates

---

software/tools/snap_maint.c

Fix for Issue #523 
Need to use range for Action Types. (Start / Stop)

SNAP: capi_maint did not decode all actions.

---

software/lib/snap.c

Time calculation did return unsigned int instead of unsigned long
Fix uses now unsigned long.

FIX Issue #521: 

---

actions/hdl_nvme_example/sw/snapblock.c
software/lib/snap.c

I considered adding the pthread_setcancelstate code to libsnap. But I reverted that change, because currently libsnap does not depend on libpthread. I decided that less dependencies is goodness and moved the code again into libsnapblock.so where we use pthreads anyhow.

SIM: Register reads and writes need to be non-cancelable using pslse

---

actions/hdl_nvme_example/sw/snap_cblk.c
actions/hdl_nvme_example/sw/snapblock.c
software/include/capiblock.h
software/include/snap_queue.h
software/include/snap_s_regs.h

I added code to do a parallel format and write if desired. Still 8KiB only. Performance for write is currently about 612MiB/sec instead of 230MiB/sec.

CBLK: Add flexible reqslot usage

---

hardware/Makefile
hardware/setup/create_framework.tcl
hardware/snap_check_psl
snap_env

If a user only wants to build a simulation model, no PSL DCP is required. 

Defect #565: allow a simulation model build without a PSL DCP

---

actions/hls_intersect/README.md
actions/hls_intersect/hw_h/action_intersect_h.H
actions/hls_intersect/hw_s/action_intersect_s.H
actions/hls_intersect/include/action_intersect.h
actions/hls_intersect/include/action_intersect_common.h

For Issue #578
For simulation in Vivado2017.4, some C data structure is more strictly checked by HLS (and set to ERROR). So I have to split the header files to 
* action_intersectXXXX.H (for `hw action`)
* action_intersectXXXX.h (for `sw action`) and 
* action_intersectXXXX_common.h (be included by the above two header files and for both.) 
Simulation passed now.

Fix #578 HLS intersect: Split header files to sw-only and common

---

README.md
software/tools/snap_find_card

Hello and happy new year !
we added information (using -v in front of all params) in the snap_find_card, without modifying the current usage (to avoid mess up automated tests)
We suggest a change in the doc for pslse to avoid user to spend long time to search for the temporary tags info.
Best regards
Alexandre

Hls snap find verbose psle doc

---

snap_env

Signed-off-by: Sven Boekholt <boekholt@de.ibm.com>

HW: Defaulting to comment instead of empty PSL_DCP in snap_env.sh

---

README.md
actions/hdl_nvme_example/hw/action_nvme_example.vhd
actions/hdl_nvme_example/sw/snapblock.c
hardware/setup/flash_mcs.tcl
hardware/sim/README.md
hardware/sim/testlist.sh
hardware/snap_check_psl
software/tools/snap_find_card

It appears to be more stable than the 16 req slot version and might be ok to try as circumvention until real problem is found.

CBLK: Add (and remove) circumvention to limit possible slots to 15 and not 16

---

hardware/sim/testlist.sh

reduce simtime from 5h to <1h by tailoring tests

less sim time for hls_search

---

hardware/hdl/core/dma_buffer_capi20.vhd_source
hardware/setup/create_framework.tcl
hardware/setup/create_nvme_host.tcl

This fixed the "NVME, empty axi_pcie3_0_0_pcie3_ip.v in vivado 2017.4" problem (#596) .  The solution is to create the NVME output products in create_nvme_host.tcl instead of create_framework.tcl

SR_10425625 fix

---

hardware/Makefile

Cleaning PSLSE on each call of  `make clean` within the SNAP framework is breaking the shared usage of one PSLSE clone by multiple SNAP clones (sandboxes).

HW: Don't clean pslse on hardware clean

---

scripts/Kconfig
software/lib/snap.c

- Kconfig : Adding help messages to different choices
- Kconfig : moving above the **Cloud build** option as first choice of Advanced option so that selecting it or not, the display stays at the same place (no functionality changes, just a cosmetic change)
- software/lib/snap.c : Answers Issue#432 - renaming a variable to be coherent

Adding Kconfig help messages - cosmetics changes

---

check_pslse.sh

'version' is a variable in check_pslse.sh, not an executable command.
Parenthesis not needed at all here.
Signed-off-by: David Epping david.epping@missinglinkelectronics.com

Sim: Fix wrong parenthesis of bash variable

---

hardware/Makefile
hardware/setup/create_framework.tcl
hardware/setup/create_ip.tcl
hardware/snap_check_psl
snap_env

Allow for model build with 'illegal' PSL_DCP and (in case of N250SP) w/o PSL4N250SP_ROOT
Fast fail for image build in case of  'illegal' PSL_DCP or missing PSL4N250SP_ROOT

HW: Modifying PSL check for image and model build

---

hardware/setup/flash_mcs.tcl
hardware/setup/snap_bitstream_post.tcl
hardware/setup/snap_bitstream_pre.tcl
hardware/setup/snap_build.tcl
software/tools/snap_maint.c

... and some more comments.
TBD: the optimal bitstream generation parameters provided by the manufacturers differ from card to card, e.g. the synchronous mode DISABLED or TYPE1, or configuration clock divider (DIV-4, DIV-1)

Correct bitstream parameters for N250S+

---

software/tools/snap_find_card

Since the bit stream contains the information, it can be misleading not to mention it.
Signed-off-by: Alexandre Castellane alexandre.castellane@fr.ibm.com

snap_find_card_update

---

hardware/doc/Bitstream_flashing.md
hardware/hdl/core/psl_fpga_ad8k5.vhd_source
hardware/hdl/core/psl_fpga_adku3.vhd_source
hardware/hdl/core/psl_fpga_n250s.vhd_source
hardware/hdl/core/psl_fpga_n250sp.vhd_source
hardware/hdl/core/psl_fpga_s121b.vhd_source
hardware/setup/snap_bitstream_pre.tcl
hardware/setup/snap_build.tcl
scripts/Kconfig

Based on branch change_factory_bit by @kenhill 
Rebased, added remaining card and made implementation the same across cards
Integrated into snap_build and Kconfig
Updated bitstream parameters for user/factory image
Todo: more detailed testing of multiboot fallback on all cards with different failure scenarios (not part of this pull request

Change factory bit to a pre-set register

---

hardware/hdl/core/mmio.vhd_source

Job sequence number is ignored now for direct access mode.
This is fixing issue #682

HW: Fixing direct access mode

---

hardware/snap_check_psl

Hi, 
I have fixed the issue of wbstart address in PSL DCP. The new dcp has already been uploaded to OpenPower Portal. 
So at this time, the md5sum check should also be refreshed. 
BTW: This is for Semptian card BPIx16 interface (ver16.1). It has another SPIx4 interface (ver16.2) and will be handled later.

Update nsa121b check psl MD5sum

---

actions/hls.mk

Looking for FPGACHIP information from $SNAP_ROOT/.snap_config 
It works and targets to solve #735  and part of #731 
For the very first time people still have to run `make snap_config` and `make model`
But when tuning the HLS hw code, they can stay in $ACTION_ROOT/hw directory and `make`.  It can shorten the iteration time in developement.

Fix actions/hls.mk to get FPGACHIP automatically

---

README.md

README and Jenkins regression moved to 2018.1, users notified via slack

recommend Vivado 2018.1 in README

---

check_pslse.sh
hardware/Makefile
hardware/setup/create_framework.tcl
scripts/Kconfig
snap_env

PSL_DCP and PSL9_IP_CORE are inserted (commented) if no snap_env.sh file
PSL_DCP and PSL9_IP_CORE can be left set in both capi1.0 or 2.0 cards configuration
PSLSE is recompiled every time to prevent errors or prevent to have p8 and p9 compiled version (adds couple of secs only)

Simplify snap env.sh use of variables

---

hardware/setup/create_framework.tcl

The CAPI BSP constraints are no longer added explicitely.
As part of the capi_bsp_wrap IP they are automatically part of the project with property PROCESSING_ORDER set to EARLY.
@luyong6: This changes requires the PCIe clock pin issue for FX609 to be fixed in `hardware/setup/FX609/snap_FX609.xdc`

Fix CAPI BSP constraints

---

hardware/setup/FX609/snap_FX609.xdc
hardware/setup/S241/snap_S241.xdc

Signed-off-by: luyong6 <luyong@cn.ibm.com>

Remove xdc mistakenly used by S241 and FX609

---

hardware/setup/create_framework.tcl

Signed-off-by: luyong6 <luyong@cn.ibm.com>
Generating scripts is time-consuming and doesn't help. I have verified it with simulation and make image. It doesn't have an impact. Please check (especially for nvme case because I didn't do it.) 
This can save the time in [CREATE_FRAMEWORK....]

Save make framework time by using -no_script

---

actions/hls_latency_eval/tests/test_0x10141009.sh
actions/hls_mm_test/tests/test_0x1014100A.sh

Signed-off-by: Lu Yong <luyong@cn.ibm.com>
Add the interrupt enable/disable choice for hls_latency and hls_mm_test testing scripts.

update two test scripts to add interrupt choice

---

ActionTypes.md
actions/README.md
actions/hls_decimal_mult/Makefile
actions/hls_decimal_mult/README.md
actions/hls_decimal_mult/hw/Makefile
actions/hls_decimal_mult/hw/action_decimal_mult.H
actions/hls_decimal_mult/hw/action_decimal_mult.cpp
actions/hls_decimal_mult/include/common_decimal.h
actions/hls_decimal_mult/sw/Makefile
actions/hls_decimal_mult/sw/action_decimal_mult.c
actions/hls_decimal_mult/sw/snap_decimal_mult.c
actions/hls_decimal_mult/tests/test_0x1014100B.sh
actions/scripts/snap_jenkins.sh
defconfig/AD8K5.hls_decimal_mult.defconfig
defconfig/ADKU3.hls_decimal_mult.defconfig
defconfig/FX609.hls_decimal_mult.defconfig
defconfig/N250S.hls_decimal_mult.defconfig
defconfig/N250SP.hls_decimal_mult.defconfig
defconfig/RCXVUP.hls_decimal_mult.defconfig
defconfig/S121B.hls_decimal_mult.defconfig
defconfig/S121B_BPIx16.hls_decimal_mult.defconfig
defconfig/S121B_SPIx4.hls_decimal_mult.defconfig
defconfig/S241.hls_decimal_mult.defconfig
hardware/sim/testlist.sh
scripts/Kconfig
snap_env

New hls_decimal_mult example to exercise single and double precision floating points

Hls decimalmult rebase2

---

actions/hls.mk
actions/scripts/create_run_hls_script.sh

I'm using defines in my HLS code to conditionally enable specific behavior.
In order to automatically enable this behavior in my CI system, I'd like to be able to pass compiler flags to HLS when `make`ing the action's hardware part.
This PR adds the necessary variables to the `create_run_hls_script.tcl` which is responsible for creating the HLS project, thereby specifying the compiler flags associated with each file.

Add mechanism to specify HLS compiler flags in action hw Makefile

---

ActionTypes.md

This adds Metal FS to the list of known Action Types, under the FB.06 vendor namespace.

Add Metal FS Action Type

---

Makefile
hardware/Makefile
hardware/sim/run_sim

When developing on a remote machine (i.e. using an SSH connection) it's not possible to run the SNAP simulation because it opens a new xterm window.
As an alternative, I have added another target to the root Makefile that allows to use the terminal multiplexer 'screen' instead. If users prefer to use that over the xterm simulator window, they can install screen on their machine and use `make sim_screen` for simulation.

Add make target for simulating in tmux

---

actions/software.mk

Currently most sw directories of actions do not have any sub-directories and therefore software.mk is also only erasing the object files created in single depth of sw. This patch allows users to erase any object files in sub-directories of sw with make clean command if they have properly set $(projs)_objs argument.

Make software.mk to clean object files more thoroughly

---

software/tools/snap_find_card

Signed-off-by: Alexandre CASTELLANE <alexandre.castellane@fr.ibm.com>

AD9H3 subdevice corrected
